# Generated by Django 4.1.1 on 2022-09-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Reference',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
